### ISSUE TITLE
How can I reset?

### ISSUE THREAD

**Issue by MaengMarco** [ronny3050/phone-notification-mirror#12]
How can I reset?
Notifications always keep.
Also The second notification is output hundreds or thousands of times.
What should I do??

**Comment by ronny3050** [comment]
Could you please send me a screenshot and logs?

**Comment by MaengMarco** [comment]
@ronny3050 Where can I see the log file?
I can not find.. :-(

**Comment by MaengMarco** [comment]
![kakaotalk_20170509_185715807](https://cloud.githubusercontent.com/assets/20651538/25845676/c11b7e16-34e9-11e7-8a93-afeea11f81da.png)


A screenshot is like this.
I fixed one problem that the second notification is output hundreds or thousands of times.
But message (no application. just SMS) is not notified.

**Comment by ronny3050** [comment]
That is great that you were able to fix the issue with long outputs!

So the issue that you're facing is that only SMS texts are shown but no notifications from other applications are shown. Am I correct? 

Pushbullet is known to support limited applications from what I hear from other people. Please let me know what applications you're trying to use.

Thanks!

**Comment by MaengMarco** [comment]
Yes, right!
I want to receive an SMS notification, which is the default message, in addition to application messages like Kakao Talk.

**Comment by ronny3050** [comment]
I am certain Kakao Talk will not be supported by Pushbullet. Common apps such as outlook, whatsapp, facebook, etc. are working AFAIK.

**Comment by MaengMarco** [comment]
@ronny3050 So how can I reset? I need your help..
I checked notifications on my phone. But there are still notifications on MagicMirror2.

**Comment by SypherDaemon** [comment]
Hello there @MaengMarco 

How did you fix the second notification from repeating hundreds of times? Right now the first notification works fine, then when second comes in, it repeats a few times, then the third notification will also repeat many times and takes up all the space.

For how to reset, instead of letting it push notifications in 'phone_notifications.js', change the "that.payload.push(newPayload) and this.payload.push(newPayload). to that.payload.unshift(newPayload) and this.payload.unshift(newPayload), this doesn't reset the notifications but at least the new ones will appear on top instead of being pushed to the bottom.
